#!/bin/sh -ex

SITE_NAME=tendenci

DB_NAME=$SITE_NAME
DB_USER=$SITE_NAME
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SITE_DIR=/var/www/$SITE_NAME
SECRET_KEY=`date | md5sum | head -c 16`

# Setup extra dependencies for PIL
[ -f /usr/lib/libz.so ] || ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/
[ -f /usr/lib/libjpeg.so ] || ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib/
[ -f /usr/lib/libfreetype.so ] || ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib/

# create the tendenci site folder
mkdir -p $SITE_DIR
cd $SITE_DIR

pip install virtualenv
virtualenv venv --distribute
. venv/bin/activate

pip install tendenci
create-tendenci-project
pip install -r requirements/dev.txt

# start postgresql
service postgresql restart

# create tendenci database
su postgres -c "createuser --no-superuser --createdb --no-createrole $DB_USER"
su postgres -c "createdb --owner $DB_USER $DB_NAME"
su postgres -c "psql postgres" << EOF
alter user $DB_USER with encrypted password '$DB_PASS';
EOF

# update DATABASE_URL in .env
sed -i "s|DATABASE_URL\s*=\(.*\)|DATABASE_URL='postgres://$DB_USER:$DB_PASS@localhost/$DB_NAME'|" .env

# add some variables in .env
echo "LOCAL_MEMCACHED_URL='127.0.0.1:11211'" >> .env
echo "EMAIL_HOST='localhost'" >> .env
echo "EMAIL_PORT='25'" >> .env
echo "HAYSTACK_SEARCH_ENGINE='whoosh'" >> .env
echo "SECRET_KEY='$SECRET_KEY'" >> .env

# run deploy.py
python deploy.py

# create tendenci superuser
cat>>$SITE_DIR/create_superuser.py<<EOF
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'conf.settings'
import conf.settings
from django.contrib.auth.models import User
User.objects.create_superuser('$ADMIN_NAME', '$ADMIN_MAIL', '$ADMIN_PASS')
EOF
python $SITE_DIR/create_superuser.py
rm $SITE_DIR/create_superuser.py

# install default data and update index
python manage.py load_npo_defaults
python manage.py update_index

# deactivate virtual environment
deactivate

# setup gunicorn
useradd tendenci -d /nonexistent
groupadd -f tendenci
usermod -a -G tendenci tendenci

mkdir -p $SITE_DIR/run
cp /var/bin/gunicorn_start.sh venv/bin/gunicorn_start
chmod +x venv/bin/gunicorn_start

# change ownership
chown -R tendenci:www-data $SITE_DIR

# setup nginx
mkdir -p /etc/nginx/sites-enabled
ln -s /etc/nginx/sites-available/$SITE_NAME /etc/nginx/sites-enabled/$SITE_NAME
rm -f /etc/nginx/sites-enabled/default

# stop postgresql
service postgresql stop

