#!/bin/sh -ex

SITE_NAME=tendenci

DB_NAME=$SITE_NAME
DB_USER=$SITE_NAME
DB_PASS=$(mcookie)

SITE_DIR=/var/www/$SITE_NAME
TENDENCI_USERNAME=admin
TENDENCI_PASSWD=admin
USER_EMAIL=root@localhost
SECRET_KEY=`date | md5sum | head -c 16`

# Setup extra dependencies for PIL
if [ ! -f /usr/lib/libz.so ]; then
        ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/
fi
if [ ! -f /usr/lib/libjpeg.so ]; then
        ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib/
fi
if [ ! -f /usr/lib/libfreetype.so ]; then
        ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib/
fi
# create the tendenci site folder
mkdir -p $SITE_DIR
cd $SITE_DIR

pip install virtualenv
virtualenv venv --distribute
. venv/bin/activate

pip install tendenci

create-tendenci-project

pip install -r requirements/dev.txt

# start postgresql
service postgresql restart

# create tendenci database
su postgres -c "createuser --no-superuser --createdb --no-createrole $DB_USER"
su postgres -c "createdb --owner $DB_USER $DB_NAME"
su postgres -c "psql postgres" << EOF
alter user $DB_USER with encrypted password '$DB_PASS';
EOF

# update DATABASE_URL in .env
sed -i "s|DATABASE_URL\s*=\(.*\)|DATABASE_URL='postgres://$DB_USER:$DB_PASS@localhost/$DB_NAME'|" .env

# add some variables in .env
echo "LOCAL_MEMCACHED_URL='127.0.0.1:11211'" >> .env
echo "EMAIL_HOST='localhost'" >> .env
echo "EMAIL_PORT='25'" >> .env
echo "HAYSTACK_SEARCH_ENGINE='whoosh'" >> .env
echo "SECRET_KEY='$SECRET_KEY'" >> .env

# run deploy.py
python deploy.py

# create tendenci superuser
cat>>$SITE_DIR/create_superuser.py<<EOF
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'conf.settings'
import conf.settings
from django.contrib.auth.models import User
User.objects.create_superuser('$TENDENCI_USERNAME', '$USER_EMAIL', '$TENDENCI_PASSWD')
EOF
python $SITE_DIR/create_superuser.py
rm $SITE_DIR/create_superuser.py

# install default data
python manage.py load_npo_defaults

# update index
python manage.py update_index

# deactivate virtual environment
deactivate

# create tendenci user and group - to be used by gunicorn
useradd tendenci -d /nonexistent
groupadd -f tendenci
usermod -a -G tendenci tendenci

# setup gunicorn
mkdir -p $SITE_DIR/run
cp /var/bin/gunicorn_start.sh venv/bin/gunicorn_start
chmod +x venv/bin/gunicorn_start

# change owner
chown -R tendenci:www-data $SITE_DIR

# create a symlink
mkdir -p /etc/nginx/sites-enabled
ln -s /etc/nginx/sites-available/$SITE_NAME /etc/nginx/sites-enabled/$SITE_NAME

# remove nginx default
rm -f /etc/nginx/sites-enabled/default

# stop services
service postgresql stop

