#!/bin/bash -e
# regenerate tendenci secret_key and tendenci db password

. /etc/default/inithooks

updateconf() {
    CONF=/var/www/tendenci/.env
    sed -i "s/^$1=\(.*\)/$1=\'$2\'/" $CONF
}

updatepgpwd() {
	CONF=/var/www/tendenci/.env
	oldpwd=`sed -n  "/^DATABASE_URL=/p" $CONF | cut -d : -f 3 | cut -d @ -f 1`
	sed -i /^DATABASE_URL/s/$oldpwd/$1/ $CONF
}

updateconf 'SECRET_KEY' $(mcookie)$(mcookie)

PASSWORD=$(mcookie)
updatepgpwd $PASSWORD
$INITHOOKS_PATH/bin/pgsqlconf.py --user=tendenci --pass="$PASSWORD"
